"""
models/schemas.py
─────────────────
Strict Pydantic v2 schemas for LifeReel AI.

Unified schema design:
  - Both text entries and audio memories share the same response schema.
  - DiaryInput    – payload for typed text entries.
  - EntryResponse – fully enriched document returned to the frontend.
  - MemoryResponse – alias of EntryResponse used by /api/memory/create.
"""

from pydantic import BaseModel, Field
from typing import List, Optional


class DiaryInput(BaseModel):
    """
    Payload accepted by POST /api/entries/generate.

    Attributes
    ----------
    raw_text:
        The unprocessed typed diary entry supplied by the user.
        Must be a non-empty string; whitespace-only strings are rejected
        by the min_length constraint.
    """

    raw_text: str = Field(
        ...,
        min_length=1,
        description="Raw diary text from the user – voice transcript or typed input.",
        examples=["Today I finally finished my capstone project. I feel exhausted but so proud."],
    )


class EntryResponse(BaseModel):
    """
    Unified document returned by all endpoints (text and audio entries).

    Attributes
    ----------
    id:
        Stringified MongoDB ObjectId.
    title:
        Poetic 3-5 word title generated by Gemini.
    transcript:
        Original raw text / Whisper transcription of the entry.
    story:
        Three-sentence elegantly reframed summary generated by Gemini.
    emotion:
        Exactly one of: Joy | Calm | Melancholy | Productive | Anxious.
    characters:
        List of people/characters mentioned in the entry.
    scene_prompt:
        Single image prompt used for Stable Diffusion image generation.
    image_url:
        Relative URL to the locally stored generated image (nullable).
    created_at:
        ISO 8601 UTC timestamp.
    """

    id: str = Field(..., description="Stringified MongoDB ObjectId.")
    user_id: Optional[str] = Field(None, description="Owner user ID.")
    title: str = Field(..., description="Poetic 3-5 word title for the diary entry.")
    transcript: str = Field(..., description="Original raw text or Whisper transcription.")
    story: str = Field(..., description="Three-sentence beautifully reframed story.")
    emotion: str = Field(..., description="Primary emotion: Joy | Calm | Melancholy | Productive | Anxious.")
    characters: List[str] = Field(default_factory=list, description="People/characters mentioned in the entry.")
    scene_prompt: str = Field(..., description="Image generation prompt for Stable Diffusion.")
    image_url: Optional[str] = Field(default=None, description="Static URL to the generated image, or null if generation failed.")
    created_at: str = Field(..., description="ISO 8601 UTC timestamp of creation.")

    model_config = {"populate_by_name": True}


class UserRegister(BaseModel):
    username: str = Field(..., min_length=2)
    email: str = Field(..., examples=["user@lifereel.ai"])
    password: str = Field(..., min_length=6)


class UserLogin(BaseModel):
    email: str = Field(...)
    password: str = Field(...)


class UserResponse(BaseModel):
    id: str
    username: str
    email: str
    joined_date: str
    avatar: str
    streak: int = 1


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user: UserResponse


# Backward-compat aliases so existing route code keeps working
DiaryResponse = EntryResponse
MemoryResponse = EntryResponse
